services:
  walera:
    environment:
      WALERA_LIMITS_GLOBAL_CONCURRENT: "60000"
      WALERA_LIMITS_PER_USER_CONCURRENT: "60000"
      WALERA_LIMITS_PER_USER_RATE_PER_SECOND: "10000"
      WALERA_LIMITS_PER_USER_BURST: "60000"
      WALERA_LIMITS_PRE_AUTH_RATE_PER_SECOND: "10000"
      WALERA_LIMITS_PRE_AUTH_BURST: "60000"
